name: Staging

on:
  pull_request:
    branches: [staging]
    types: [opened, synchronize, reopened]
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    env:
      working_directory: ./nodejs-fullstack

    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ${{ env.working_directory }}/pnpm-lock.yaml

      - name: Load secrets
        uses: Infisical/secrets-action@v1.0.9
        with:
          method: universal
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          domain: ${{ secrets.INFISICAL_DOMAIN }}
          env-slug: staging
          project-slug: nodejs-fullstack-template
          export-type: env

      - name: Debug
        run: |
          printenv

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ${{ env.working_directory }}

      # - name: Typecheck
      #   run: pnpm typecheck
      #   working-directory: ${{ env.working_directory }}

      - name: Lint
        run: pnpm lint
        working-directory: ${{ env.working_directory }}

      - name: Build
        run: pnpm build
        working-directory: ${{ env.working_directory }}

      - name: Test
        run: pnpm test -- --coverage
        working-directory: ${{ env.working_directory }}

      - name: Security audit
        run: pnpm audit
        working-directory: ${{ env.working_directory }}

      - name: Deploy docs
        run: |
          pnpm --filter @nodejs-fullstack-template/docs build:vercel
          pnpm --filter @nodejs-fullstack-template/docs deploy:vercel -- --target staging
        working-directory: ${{ env.working_directory }}
